### ISSUE TITLE
`resize` not implemented

### ISSUE THREAD

**Issue by YibaiMeng** [LBL-EESA/HAMR#42]
`resize` for `hamr::Buffer<T>` is a NO-OP at the moment, although it's in the docs.

**Comment by burlen** [comment]
@YibaiMeng, Thanks for the report. `buffer::resize` is implemented and I've just now added a regression test to verify that it is working (link below). If looking at the test does not help, I need more information to diagnose. Could you share the cmake command line (or the options you are using to configure cmake) and a small snippet of code to reproduce? 

https://github.com/LBL-EESA/HAMR/pull/43/files#diff-bd35e2220260d7321b73358e804e8885df97e76f2f4f75d290c0585d14970626

**Comment by YibaiMeng** [comment]
Nevermind, I was using a older version, and the docs I was reading didn't match the code.

Thanks for adding the test!

**Comment by burlen** [comment]
@YibaiMeng no worries. please do reach out if there are any issues like this. If nothing else it will motivate me to improve our test coverage.
